#pragma once

#define WINCX 640
#define WINCY 480


#define TITLE_SCREEN_CX 640
#define TITLE_SCREEN_CY 480

#define TITLE_START_CX 75
#define TITLE_START_CY 30

#define TITLE_QUIT_CX 60
#define TITLE_QUIT_CY 25

#define STAGE_UI_MENU_CX 64
#define STAGE_UI_MENU_CY 220

#define STAGE_UI_LOGO_CX 165
#define STAGE_UI_LOGO_CY 232

#define STAGE_UI_STATE_CX 82
#define STAGE_UI_STATE_CY 223

#define STAGE_UI_LIFE_CX 13
#define STAGE_UI_LIFE_CY 13

#define STAGE_UI_BOMB_CX 13
#define STAGE_UI_BOMB_CY 13

#define STAGE_UI_NUMBER_CX 14
#define STAGE_UI_NUMBER_CY 14

#define SMALL_EFFECT_BOMB_4_CX 28
#define SMALL_EFFECT_BOMB_4_CY 28


#define STAGE_SCREEN_CX 385
#define STAGE_SCREEN_CY 450

#define ObjMgr	CObjMgr::GetInstance()