#pragma once


///////////////////////// TYPE /////////////////////////

enum RETURN_TYPE { RETURN_NULL, RETURN_DEAD, RETURN_SCENECHANGE, RETURN_END };

enum RENDER_TYPE { RENDER_OBJ, RENDER_EFFECT, RENDER_END };

enum SCENE_TYPE { SCENE_INTRO, SCENE_TITLE, SCENE_SELECT, SCENE_STAGE, SCENE_ENDING, SCENE_END };

enum CHANNEL_TYPE { CHANNEL_PLAYER, CHANNEL_MONSTER, CHANNEL_EFF, CHANNEL_BGM, CHANNEL_END };

enum OBJ_TYPE 
{
	OBJ_UIBACK,
	OBJ_STAGEBACK,
	OBJ_PLAYER,
	OBJ_PLAYERNORMALBULLET,
	OBJ_PLAYERSEARCHBULLET,
	OBJ_PLAYERBOMB,
	OBJ_PLAYERSUBWEAPON,
	OBJ_MONSTER,
	OBJ_MONSTER_BULLET,
	OBJ_ITEM,
	OBJ_PLAYERBULLETEFFECT,
	OBJ_EFFECT,
	OBJ_END
};

enum ITEM_TYPE { ITEM_BIGPOWER, ITEM_POWER, ITEM_LIFE, ITEMTYPE_END };

enum PLAYERBULLET_TYPE { PLAYERBULLET_NORMAL, PLAYERBULLET_SEARCH, PLAYERBULLET_BOMB, PLAYERBULLET_END };

enum PLAYERBULLETEFF_TYPE { PLAYERBULLETEFF_RED, PLAYERBULLETEFF_BLUE, PLAYERBULLETEFF_END };


///////////////////////// STATE /////////////////////////

enum PLAYERSTATE { PLAYER_IDLE, PLAYER_MOVE, PLAYERSTATE_END };
enum PLAYERDIR { PLAYER_LEFT, PLAYER_RIGHT, PLAYERDIR_END };

enum PLAYERSUBWEPAON_DIR { PLAYERSUBWEPAON_LEFT, PLAYERSUBWEPAON_RIGHT, PLAYERSUBWEPAON_END };

enum eTextureType
{
	TEX_SINGLE,
	TEX_MULTI,
	TEX_END,
};

enum eMONSTER_TYPE
{
	MONSTER_EASY,
	MONSTER_NOMAL,
	MONSTER_BOSS,
	MONSTER_END,
};

enum eMONSTER_PATTON
{
	M_PATTON_ONE,
	M_PATTON_TWO,
	M_PATTON_THREE,
	M_PATTON_FOUR,
	M_PATTON_FIVE,
	M_PATTON_SIX,
	M_PATTON_END,
};

enum eEFFECT_TYPE
{
	EFFECT_NOMAL,
	EFFECT_MID,
	EFFECT_16_B,

	EFFECT_PATTON_A_1,
	EFFECT_PATTON_A_2,
	EFFECT_PATTON_A_3,
	EFFECT_PATTON_A_4,
	EFFECT_PATTON_A_5,

	EFFECT_PATTON_B_1,
	EFFECT_PATTON_B_2,
	EFFECT_PATTON_B_3,
	EFFECT_PATTON_B_4,

	EFFECT_PATTON_C_1,

	EFFECT_PATTON_D_1,
	EFFECT_PATTON_D_2,
	EFFECT_PATTON_D_3,
	EFFECT_PATTON_D_4,

	EFFECT_PATTON_E_1,
	EFFECT_PATTON_E_2,
	EFFECT_PATTON_E_3,

	EFFECT_PATTON_F_1,

	EFFECT_PATTON_G_1,
	EFFECT_PATTON_G_2,

	EFFECT_PATTON_H_1,
	EFFECT_PATTON_H_2,

	EFFECT_PATTON_I_1,
	EFFECT_PATTON_I_2,
	EFFECT_PATTON_I_3,

	EFFECT_PATTON_J_1,

	EFFECT_END,
};

enum eBULLET_TYPE
{
	BULLET_TYPE_ANGLE,
	BULLET_TYPE_ANGLE_TWO,
	BULLET_TYPE_ANGLE_ALL,
	BULLET_TYPE_ANGLE_ALL_TWO,
	BULLET_TYPE_GUIDED,
	BULLET_TYPE_ANGLE_FAST,
	BULLET_TYPE_ANGLE_FAST_TWO,
	BULLET_TYPE_HELL,
	BULLET_TYPE_HELL_TWO,
	BULLET_TYPE_HELL_THREE,
	BULLET_TYPE_END,
};

enum eBULLET_NUMBER
{
	BULLET_NUMBER_ZERO,
	BULLET_NUMBER_ONE,
	BULLET_NUMBER_TWO,
	BULLET_NUMBER_THREE,
	BULLET_NUMBER_FOUR,
	BULLET_NUMBER_FIVE,
	BULLET_NUMBER_SIX,
	BULLET_NUMBER_SEVEN,
	BULLET_NUMBER_EIGHT,
	BULLET_NUMBER_NINE,
	BULLET_NUMBER_END,
};

enum eBULLET_COLOR
{
	BULLET_COLOR_BLUE,
	BULLET_COLOR_RED,
	BULLET_COLOR_GREEN,
	BULLET_COLOR_YELLOW,
	BULLET_COLOR_END,
};